language: node_js
node_js:
- stable
install:
- wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.55.6/hugo_0.55.6_Linux-64bit.deb
- sudo dpkg -i /tmp/hugo.deb
script:
- node .travis/update-version.js
- hugo
after_success:
- cd docs; rm speeddial.xpi; zip -r speeddial.xpi *; cd ..
- sudo sh .travis/push.sh
env:
  global:
  - secure: YafQZcFHF5n+L3Rw1p3eqkVbzIkMEBoekXoer/19JDIZiwoLJ9UamXLT8RXhKB7MElzXnYVn9MvJTKGAX2N9J98tlnbls7G+M/L1ah8G7uVPNi4hhdfEFqNE71NEENUqEyruDTjX/AkuplCHeE6NGx66A5v6GqdvJT+jp0RkXLTZ3XfPZdELDmy0GOiL2lXtse8EgW6lsA2jl/LdvHh037IW6H4opYQvn0OhdCMIV+62+k+OGKUHlaw1pX+6e7KaPkgt6lFgHYd+dOnIG0VCZlSeD2d9iprJPO4OOv7MmcbNP1952c1mLFw4BlFWol9uKTcykW3qTI5Vx7nh8z2touxpIED+egEU/BN9iohzLsjgONAQ8d+sjecifRxQ4FJEzzii652e41bFFoQiuV26133xOFu3M0niYxeGuLGGW7EzU4B5/Nlja4tx9/ftMREyhZ+7STYdC3UWatnGw0aksvLV4LUYWcNSvFBi8sLIA67qX6qYdMC790yXhJFjL6Y0zJN4nrNyeRzJLGEMuL8nPVZAjGveO3huFsOJNpGu+hQz5W39nItnNMnMSPChPOan+WNW/ujHoJ7lRJDcrMRBlJpuk+XqNZ+FyNE4VJ147qLW14F2WJitEN5Xrf8MFWxom+x8hvwZwYdPasNPskq8Kb+wA/2qInlqOCoRp3jyJds=
